In [1]:
import pandas as pd
import numpy as np

In [2]:
test_return = pd.read_csv("total_model_average.csv", header=0, index_col=0)

In [3]:
test_return

                GRPO       PPO       SAC
2019-01-30 -0.023335  0.019726  0.030210
2019-02-28  0.015721  0.009734  0.006705
2019-03-28 -0.008980 -0.008134 -0.010164
2019-04-26  0.002209  0.021928  0.012148
2019-05-24 -0.011915 -0.027820 -0.020592
...              ...       ...       ...
2024-09-20  0.011247  0.001493  0.032385
2024-10-18  0.010479  0.016962  0.004471
2024-11-15 -0.022477 -0.020190 -0.031152
2024-12-16  0.065416  0.078830  0.036831
2024-12-31 -0.016992 -0.000110 -0.012707

[76 rows x 3 columns]

In [5]:
# grpo_best = grpo_best[["equal_asset_weight"]]
# grpo_best.rename(columns={"equal_asset_weight": "Model"}, inplace=True)

In [12]:
test_return[test_return["SAC"] >=0]["SAC"].describe()

/tmp/ipykernel_2539832/70665978.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_return[test_return["SAC"] >=0]["SAC"].describe()

count    48.000000
mean      0.026392
std       0.018821
min       0.000017
25%       0.007894
50%       0.025345
75%       0.041514
max       0.071911
Name: SAC, dtype: float64

In [13]:
test_return[test_return["SAC"] <0]["SAC"].describe()

/tmp/ipykernel_2539832/2843672022.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  test_return[test_return["SAC"] <0]["SAC"].describe()

count    28.000000
mean     -0.027943
std       0.029781
min      -0.130886
25%      -0.032764
50%      -0.022524
75%      -0.008459
max      -0.000778
Name: SAC, dtype: float64

In [1]:
print("profitabel_months:", (test_return[col] > 0).sum())
print("unprofitabel_months:", (test_return[col] < 0).sum())

NameError: name 'test_return' is not defined

In [6]:
for col in test_return.columns:
    model = test_return[col]
    gross_profit = model[model >= 0].sum()
    gross_loss = model[model < 0].sum()
    profit_factor = gross_profit / abs(gross_loss) if gross_loss != 0 else np.nan
    print(f"gross_profit for {col}: {gross_profit:.4f}")
    print(f"gross_loss for {col}: {gross_loss:.4f}")
    print(f"Profit Factor for {col}: {profit_factor:.4f}")
    print("profitabel_months:", (test_return[col] > 0).sum())
    print("unprofitabel_months:", (test_return[col] < 0).sum())
    print("-"*50)

gross_profit for GRPO: 1.8103
gross_loss for GRPO: -0.7347
Profit Factor for GRPO: 2.4639
profitabel_months: 49
unprofitabel_months: 27
--------------------------------------------------
gross_profit for PPO: 1.9850
gross_loss for PPO: -1.1483
Profit Factor for PPO: 1.7286
profitabel_months: 44
unprofitabel_months: 32
--------------------------------------------------
gross_profit for SAC: 1.2668
gross_loss for SAC: -0.7824
Profit Factor for SAC: 1.6191
profitabel_months: 48
unprofitabel_months: 28
--------------------------------------------------

In [7]:
model

2019-01-30    0.030210
2019-02-28    0.006705
2019-03-28   -0.010164
2019-04-26    0.012148
2019-05-24   -0.020592
                ...
2024-09-20    0.032385
2024-10-18    0.004471
2024-11-15   -0.031152
2024-12-16    0.036831
2024-12-31   -0.012707
Name: SAC, Length: 76, dtype: float64

In [8]:
model.index.year

AttributeError: 'Index' object has no attribute 'year'

In [9]:
for col in test_return.columns:
    model = test_return[col]
    model.index = pd.to_datetime(model.index)
    
    # Series → DataFrame 변환
    model_df = model.to_frame(name='return')
    model_df['year'] = model_df.index.year

    yearly_return = model_df.groupby('year')['return'].sum()
    
    profitable_years = (yearly_return >= 0).sum()
    unprofitable_years = (yearly_return < 0).sum()
    
    print(f"Profitable years for {col}: {profitable_years}, Unprofitable years: {unprofitable_years}")

Profitable years for GRPO: 6, Unprofitable years: 0
Profitable years for PPO: 6, Unprofitable years: 0
Profitable years for SAC: 5, Unprofitable years: 1

In [ ]:
    # 1. 인덱스를 datetime 형식으로 변환
grpo_best.index = pd.to_datetime(grpo_best.index)
grpo_best['year'] = grpo_best.index.year
yearly_return = grpo_best.groupby('year')['Model'].sum()
# 4. 수익이 난 해 / 손실이 난 해 개수
profitable_years = (yearly_return > 0).sum()
unprofitable_years = (yearly_return <= 0).sum()

print(f"Profitable years: {profitable_years}, Unprofitable years: {unprofitable_years}")

In [9]:
gross_profit

Model    1.568973
dtype: float64

In [10]:
gross_loss = abs(grpo_best[grpo_best["Model"] < 0].sum())

In [22]:
grpo_best[grpo_best["Model"] < 0].describe()

           Model
count  32.000000
mean   -0.019697
std     0.020360
min    -0.087862
25%    -0.023889
50%    -0.016266
75%    -0.005670
max    -0.000666

In [23]:
(grpo_best<0).sum()

Model    32
dtype: int64

In [11]:
gross_loss

Model    0.630309
dtype: float64

In [12]:
profit_factor = gross_profit.values / gross_loss.values if gross_loss.values != 0 else np.inf

In [13]:
profit_factor

array([2.48921445])

In [16]:
print("profitable_month" , (grpo_best>=0).sum()
        , "unprofitable_month" , (grpo_best<0).sum())

profitable_month Model    44
dtype: int64 unprofitable_month Model    32
dtype: int64

In [ ]:
# 1. 인덱스를 datetime 형식으로 변환
grpo_best.index = pd.to_datetime(grpo_best.index)
grpo_best['year'] = grpo_best.index.year
yearly_return = grpo_best.groupby('year')['Model'].sum()
# 4. 수익이 난 해 / 손실이 난 해 개수
profitable_years = (yearly_return > 0).sum()
unprofitable_years = (yearly_return <= 0).sum()

print(f"Profitable years: {profitable_years}, Unprofitable years: {unprofitable_years}")

In [ ]:

# 3. 연도별 수익률 합계

Profitable years: 5, Unprofitable years: 1