In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
future_before_df = pd.read_csv("../data/before_future_train_v3.csv", index_col=0)
future_train_df = pd.read_csv("../data/future_train_v3.csv", index_col=0)
future_test_df = pd.read_csv("../data/future_test_v3.csv", index_col=0)
future_tot_train_df = pd.concat([future_before_df, future_train_df], axis=0)
future_tot_train_df.reset_index(drop=True, inplace=True)
future_tot_train_df = pd.concat([future_tot_train_df, future_test_df], axis=0)
future_tot_train_df.reset_index(drop=True, inplace=True)
future_tot_train_df.sort_values(by=['date', 'tic_code'], inplace=True)
future_tot_train_df.reset_index(drop=True, inplace=True)

In [5]:
before_df = pd.read_csv("../data/before_train_v3.csv", index_col=0)
train_df = pd.read_csv("../data/train_v3.csv", index_col=0)
test_df = pd.read_csv("../data/test_v3.csv", index_col=0)
tot_train_df = pd.concat([before_df, train_df], axis=0)
tot_train_df.reset_index(drop=True, inplace=True)
tot_train_df = pd.concat([tot_train_df, test_df], axis=0)
tot_train_df.reset_index(drop=True, inplace=True)
tot_train_df.sort_values(by=['date', 'tic_code'], inplace=True)
tot_train_df.reset_index(drop=True, inplace=True)

In [6]:
del_list = [ "Malaysia", "Mexico", "Italy", "Heating Oil", "Silver", "Corn"]
future_train_df = future_train_df[~future_train_df["ticker"].isin(del_list)]
future_test_df = future_test_df[~future_test_df["ticker"].isin(del_list)]
train_df = train_df[~train_df["ticker"].isin(del_list)]
test_df = test_df[~test_df["ticker"].isin(del_list)]

In [11]:
future_train_df.sort_values(by=['date', 'tic_code'], inplace=True)
future_train_df.reset_index(drop=True, inplace=True)
future_test_df.sort_values(by=['date', 'tic_code'], inplace=True)
future_test_df.reset_index(drop=True, inplace=True)

In [14]:

train_df.sort_values(by=['date', 'tic_code'], inplace=True)
train_df.reset_index(drop=True, inplace=True)
test_df.sort_values(by=['date', 'tic_code'], inplace=True)
test_df.reset_index(drop=True, inplace=True)

In [16]:


train_df.to_csv("../data/train_del_asset_v1.csv", index=False)
test_df.to_csv("../data/test_del_asset_v1.csv", index=False)
future_train_df.to_csv("../data/future_train_del_asset_v1.csv", index=False)
future_test_df.to_csv("../data/future_test_del_asset_v1.csv", index=False)

In [4]:
selected_feat = ['date', 'tic_code', 'close', 'ticker',
       'ret', 'high_ratio', 'low_ratio', 'adjust_close', 'adjust_high',
       'adjust_low', 'return_1m', 'return_3m', 'return_6m', 'return_12m',
       'return_avg', 'mom_12m', 'mom_score', 'close_1_month', 'close_2_month',
       'close_3_month', 'close_4_month', 'close_5_month', 'close_6_month',
       'close_7_month', 'close_8_month', 'close_9_month', 'close_10_month',
       'close_11_month', 'close_12_month', 'SMA_30', 'SMA_60', 'SMA_220',
       'SMA_252', 'macd', 'boll_ub', 'boll_lb', 'rsi', 'cci', 'paa_score',
       'gtaa_buy_signal', 'paa_buy_signal', 'daa_buy_signal',
       'momentum_product', 'dm_buy_signal', 'adjust_close_norm',
       'return_1m_norm', 'return_3m_norm', 'return_6m_norm', 'return_12m_norm',
       'return_avg_norm', 'mom_12m_norm', 'mom_score_norm', 'SMA_30_norm',
       'SMA_60_norm', 'SMA_220_norm', 'SMA_252_norm', 'macd_norm',
       'boll_ub_norm', 'boll_lb_norm', 'rsi_norm', 'cci_norm']

In [5]:
eqaul_df = pd.concat([tot_train_df[selected_feat], future_tot_train_df[selected_feat]])

In [6]:
eqaul_df.sort_values(by=['date', 'tic_code'], inplace=True)
eqaul_df.reset_index(drop=True, inplace=True)

In [7]:
eqaul_df

,date,tic_code,close,ticker,ret,high_ratio,low_ratio,adjust_close,adjust_high,adjust_low,...,mom_score_norm,SMA_30_norm,SMA_60_norm,SMA_220_norm,SMA_252_norm,macd_norm,boll_ub_norm,boll_lb_norm,rsi_norm,cci_norm
0,2000-09-06,CC=F,780.000000,Cocoa,0.000000,1.000000,0.987179,1.000000,1.000000,0.987179,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2000-09-06,CL=F,34.950001,Crude Oil,0.000000,1.000000,0.967954,1.000000,1.000000,0.967954,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2000-09-06,CT=F,64.360001,Cotton,0.000000,1.010721,0.995960,1.000000,1.010721,0.995960,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2000-09-06,GC=F,274.200012,Gold,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2000-09-06,HG=F,0.901500,Copper,0.000000,1.004992,0.995563,1.000000,1.004992,0.995563,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179485,2024-12-31,NG=F,3.633000,Natural Gas,-0.076982,1.104322,0.984586,0.717275,0.792103,0.706219,...,0.417865,0.107888,0.065272,-0.041547,-0.059749,0.613319,0.122847,0.096998,0.667847,0.565106
179486,2024-12-31,SB=F,19.260000,Sugar,0.006796,1.004673,0.988577,1.855491,1.864162,1.834297,...,0.261912,0.562301,0.600250,0.641475,0.660120,0.419079,0.552287,0.536710,0.143742,0.397263
179487,2024-12-31,SI=F,28.940001,Silver,-0.005703,1.007947,1.000000,5.807747,5.853904,5.807747,...,0.354140,0.710863,0.768491,0.773915,0.761310,0.417984,0.599395,0.696590,0.165471,0.452410
179488,2024-12-31,ZC=F,458.500000,Corn,0.013820,1.001091,0.985823,2.461745,2.464430,2.426846,...,0.582307,0.395003,0.387515,0.405509,0.418775,0.564215,0.394796,0.400718,0.639153,0.652550
179489,2024-12-31,ZL=F,39.779999,Soybean Oil,0.001511,1.002514,0.990448,2.574757,2.581230,2.550162,...,0.357557,0.490587,0.539664,0.667892,0.694218,0.370658,0.460958,0.469628,0.255357,0.349192

In [10]:
TRAIN_START_DATE = '2002-02-05'
TRAIN_END_DATE = '2012-12-31'

TRADE_START_DATE = '2013-01-01'
TRADE_END_DATE = '2024-12-31'

# TRAIN_START_DATE = '2000-01-10'
# TRAIN_END_DATE = '2023-12-31'
# TRADE_START_DATE = '2010-01-01'
# TRADE_END_DATE = '2023-12-31'

window_days = 252
start_day = 252
top_k = 5
top_pct = 0.5
risk_free_rate = 0
gamma = 10
rebalance_every = 20
cost = 0.003
annual_factor = 252

In [11]:
equal_price = eqaul_df[["date", "ticker", "close"]].dropna()

In [12]:
equal_df = equal_price.pivot(index="date", columns="ticker", values="close")

In [13]:
equal_df = equal_df.sort_index()

In [14]:
equal_return = equal_df.pct_change().fillna(0)

In [15]:
# ✅ 평균-분산 (Mean-Variance), 최소분산 (MinVar), 리스크패리티 (Risk-Parity), Max Sharpe
# 전략들의 차이는 "최적화 기준"의 차이뿐이며, 백테스트 로직 구조는 거의 동일함

import numpy as np
import pandas as pd
import cvxpy as cp
import matplotlib.pyplot as plt

# ✅ 평균-분산 최적화 함수 (공매도 금지)

# ✅ 최소분산 포트폴리오 (Min-Var)
def compute_minvar_weights(mu, cov_matrix):
    n = cov_matrix.shape[0]
    w = cp.Variable(n)
    objective = cp.Minimize(cp.quad_form(w, cov_matrix))
    constraints = [cp.sum(w) == 1, w >= 0]
    prob = cp.Problem(objective, constraints)
    prob.solve()
    return w.value


# ✅ 리스크 패리티 가중치 (역분산 기반 근사)
def compute_risk_parity_weight_from_window(returns_window):
    var = returns_window.var()
    inv_var = 1 / var
    weights = inv_var / inv_var.sum()
    return weights


def compute_max_sharpe_min_var(mu, cov_matrix, risk_free_rate=0.0, max_vol=None, target_return=0):
    n = len(mu)
    x = cp.Variable(n)
    excess_mu = mu - risk_free_rate
    w_tilde = cp.Variable(n)  # 치환된 weight (w_tilde = k * w)
    k = cp.Variable(nonneg=True)  # 스케일 변수
    objective = cp.Minimize(cp.quad_form(w_tilde, cov_matrix))

    constraints = [
        excess_mu.T @ w_tilde == 1,   # 초과수익률 고정
        cp.sum(w_tilde) == k,          # w_tilde = k * w
        w_tilde >= 0          # w_tilde = k * w
    ]


    prob = cp.Problem(objective, constraints)
    prob.solve()
    
    if w_tilde.value is not None and k.value is not None and k.value > 0:
        w = w_tilde.value / k.value
        return w
    else:
        print("최적화 실패. 균등 포트폴리오로 fallback.")
        return np.zeros(n)

# ✅ 백테스트 공통 함수 (최적화 함수 인자로 받음)
def backtest_strategy(returns, compute_weights_fn, rebalance_every=20, window_days=252, cost=0.003, start_day=252, **kwargs):
    dates = returns.index
    portfolio_returns = []
    weights_record = []
    prev_weights = None

    i = start_day
    while i < len(dates) - rebalance_every:
        window_data = returns.iloc[i - window_days:i]
        # print(f"Window data shape: {window_days}")
        if window_data.isna().sum().sum() > 0:
            i += rebalance_every
            continue

        mu = window_data.mean().values
        cov = window_data.cov().values

        # mu = window_data.mean().values
        # cov = window_data.cov().values
        try:
            weights = compute_weights_fn(mu, cov, **kwargs)
        except TypeError:
            weights = compute_weights_fn(window_data, **kwargs)

        if weights is None:
            i += rebalance_every
            continue

        n_assets = returns.shape[1]
        
        if prev_weights is None:
            prev_weights = np.zeros(n_assets)

        if i + rebalance_every < len(dates) - rebalance_every:
            sub_returns = returns.iloc[i:i + rebalance_every]
        else:
            sub_returns = returns.iloc[i:]
            
        for j, (date, row) in enumerate(sub_returns.iterrows()):
            if j == 0 and prev_weights is not None:
                turnover = np.abs(weights - prev_weights).sum()
                tc = turnover * cost
            else:
                tc = 0
            daily_ret = np.dot(weights, row.fillna(0)) - tc
            portfolio_returns.append((date, daily_ret))
            weights_record.append((date, weights))

        prev_weights = weights
        i += rebalance_every

    strat_returns = pd.Series(dict(portfolio_returns)).sort_index()
    strat_weights = pd.DataFrame({d: w for d, w in weights_record}).T
    return strat_returns, strat_weights

## 다른 전략

In [16]:
change_asset_return = equal_return.copy()

In [17]:
change_asset_return = change_asset_return.drop(columns=[ "Malaysia", "Mexico", "Italy", "Heating Oil", "Silver", "Corn"], axis=1)

In [18]:
# 3. 리스크 패리티 (Risk-Parity)
rp_returns, rp_weights = backtest_strategy(
    equal_return,
    compute_weights_fn=compute_risk_parity_weight_from_window,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost = cost
)

In [19]:
minvar_returns, minvar_weights = backtest_strategy(
    equal_return,
    compute_weights_fn=compute_minvar_weights,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost=cost
)

In [20]:
ms_returns, ms_weights = backtest_strategy(
    equal_return,
    compute_weights_fn=compute_max_sharpe_min_var,
    risk_free_rate=risk_free_rate,  # 무위험 수익률
    target_return=0.0,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost =cost


    # max_vol=0.01   # 최대 변동성 제약 (선형 근사)
)

/opt/conda/lib/python3.11/site-packages/cvxpy/problems/problem.py:1504: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(

최적화 실패. 균등 포트폴리오로 fallback.

In [21]:
# 3. 리스크 패리티 (Risk-Parity)
ch_rp_returns, ch_rp_weights = backtest_strategy(
    change_asset_return,
    compute_weights_fn=compute_risk_parity_weight_from_window,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost = cost
)

In [22]:
ch_minvar_returns, ch_minvar_weights = backtest_strategy(
    change_asset_return,
    compute_weights_fn=compute_minvar_weights,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost=cost
)

In [23]:
ch_ms_returns, ch_ms_weights = backtest_strategy(
    change_asset_return,
    compute_weights_fn=compute_max_sharpe_min_var,
    risk_free_rate=risk_free_rate,  # 무위험 수익률
    target_return=0.0,
    rebalance_every=rebalance_every,
    window_days=window_days,
    start_day = start_day,
    cost =cost


    # max_vol=0.01   # 최대 변동성 제약 (선형 근사)
)

/opt/conda/lib/python3.11/site-packages/cvxpy/problems/problem.py:1504: UserWarning: Solution may be inaccurate. Try another solver, adjusting the solver settings, or solve with verbose=True for more information.
  warnings.warn(

최적화 실패. 균등 포트폴리오로 fallback.

In [24]:
def backtest_paa_from_pivot(returns: pd.DataFrame,
                             pivot_score: pd.DataFrame,
                             window_days: int = 252,
                             rebalance_every: int = 20,
                             top_n: int = 10,
                             score_threshold: float = 0.0,
                             cost: float = 0.003,
                             start_day: int = 252):
    """
    PAA 전략 백테스트 (수익률 기반 점수 사용, 거래비용 반영)

    Parameters:
    - returns: 일간 수익률 DataFrame (index: date, columns: tickers)
    - pivot_score: PAA score DataFrame (index: date, columns: tickers)
    - window_days: 과거 데이터 시작 시점
    - rebalance_every: 리밸런싱 주기
    - top_n: 상위 자산 수
    - score_threshold: 점수 필터링 기준
    - cost: 거래 비용 비율

    Returns:
    - paa_returns: 전략 일간 수익률 Series
    - paa_weights: 전략 리밸런싱 시점별 자산 비중 DataFrame
    """
    dates = returns.index
    portfolio_returns = []
    weights_record = []
    prev_weights = pd.Series(0, index=returns.columns, dtype=float)

    i = start_day
    while i < len(dates) - rebalance_every:
        current_date = dates[i]
        score_today = pivot_score.loc[current_date]
        satisfied_assets = score_today[score_today > score_threshold]
        if satisfied_assets.empty:
            selected = []
        else:
            selected = satisfied_assets.sort_values(ascending=False).head(top_n).index

        weights = pd.Series(0, index=returns.columns, dtype=float)
        if len(selected) > 0:
            weights[selected] = 1 / len(selected)

        if i + rebalance_every < len(dates) - rebalance_every:
            sub_returns = returns.iloc[i:i + rebalance_every]
        else:
            sub_returns = returns.iloc[i:]
                    
        for j, (date, row) in enumerate(sub_returns.iterrows()):
            tc = np.abs(weights - prev_weights).sum() * cost if j == 0 else 0
            daily_ret = np.dot(weights, row.fillna(0)) - tc
            portfolio_returns.append((date, daily_ret))
            weights_record.append((date, weights.copy()))

        prev_weights = weights.copy()
        i += rebalance_every

    paa_returns = pd.Series(dict(portfolio_returns)).sort_index()
    paa_weights = pd.DataFrame({d: w for d, w in weights_record}).T
    return paa_returns, paa_weights

In [26]:
all_paa_score = eqaul_df.pivot(index='date', columns='ticker', values='paa_score')

In [29]:
ch_all_paa_score = all_paa_score.copy()

In [31]:
ch_all_paa_score = ch_all_paa_score.drop(columns=[ "Malaysia", "Mexico", "Italy", "Heating Oil", "Silver", "Corn"], axis=1)

In [32]:
paa_returns, paa_weights = backtest_paa_from_pivot(
    equal_return, all_paa_score,
    top_n=top_k,
    window_days = window_days,
    rebalance_every=rebalance_every,
    score_threshold=0.0,
    cost=cost
)

In [37]:
ch_paa_returns, ch_paa_weights = backtest_paa_from_pivot(
    change_asset_return, ch_all_paa_score,
    top_n=top_k,
    window_days = window_days,
    rebalance_every=rebalance_every,
    score_threshold=0.0,
    cost=cost
)

In [38]:
def backtest_equal_weight_20day(returns: pd.DataFrame, rebalance_every=20, window_days=252, cost=0.003, start_day=252):
    dates = returns.index
    portfolio_returns = []
    weights_record = []
    prev_weights = None

    i = start_day
    while i < len(dates) - rebalance_every:
        rebalance_day = dates[i]
        window_data = returns.iloc[i - window_days:i]


        n_assets = window_data.shape[1]
        weights = np.ones(n_assets) / n_assets  # 1/N 포트폴리오
        n_assets = returns.shape[1]
        if prev_weights is None:
            prev_weights = np.zeros(n_assets)  # 최초 리밸런싱: 전량 매수로 간주
            
        if i + rebalance_every < len(dates) - rebalance_every:
            sub_returns = returns.iloc[i:i + rebalance_every]
        else:
            sub_returns = returns.iloc[i:]

        for j, (date, row) in enumerate(sub_returns.iterrows()):
            if j == 0 and prev_weights is not None:
                turnover = np.abs(weights - prev_weights).sum()
                tc = turnover * cost
            else:
                tc = 0
            daily_ret = np.dot(weights, row.fillna(0)) - tc
            portfolio_returns.append((date, daily_ret))
            weights_record.append((date, weights))

        prev_weights = weights
        i += rebalance_every

    ew_returns = pd.Series(dict(portfolio_returns)).sort_index()
    ew_weights = pd.DataFrame({d: w for d, w in weights_record}).T
    return ew_returns, ew_weights

In [39]:
# 백테스트 실행
equal_returns, equal_weights = backtest_equal_weight_20day(equal_return, rebalance_every=rebalance_every, window_days=window_days, cost=cost)

# Sharpe 비율 계산
# equal_sharpe = equal_returns.mean() / equal_returns.std() * np.sqrt(252)

In [40]:
ch_equal_returns, ch_equal_weights = backtest_equal_weight_20day(change_asset_return, rebalance_every=rebalance_every, window_days=window_days, cost=cost)

In [41]:
strategy_returns = {
    'risk_parity': rp_returns,
    'minvar': minvar_returns,
    'max_shapre': ms_returns,
    'paa' : paa_returns,
    'Equal Weight': equal_returns
}

In [45]:
ch_strategy_returns = {
    'risk_parity': ch_rp_returns,
    'minvar': ch_minvar_returns,
    'max_shapre': ch_ms_returns,
    'paa' : ch_paa_returns,
    'Equal Weight': ch_equal_returns
}

In [46]:
risk_cum = (1 + rp_returns).cumprod()
minvar_cum = (1 + minvar_returns).cumprod()
ms_cum = (1 + ms_returns).cumprod()
paa_cum = (1 + paa_returns).cumprod()
equal_cum = (1 + equal_returns).cumprod()

In [47]:
ch_risk_cum = (1 + ch_rp_returns).cumprod()
ch_minvar_cum = (1 + ch_minvar_returns).cumprod()
ch_ms_cum = (1 + ch_ms_returns).cumprod()
ch_paa_cum = (1 + ch_paa_returns).cumprod()
ch_equal_cum = (1 + ch_equal_returns).cumprod()

In [48]:
import os
import sys
# 현재 경로의 부모 디렉토리
parent_dir = os.path.dirname(os.getcwd())

# sys.path에 현재 경로와 부모 경로 추가
sys.path.append(parent_dir)
import eval_metric as em

In [49]:
def calculate_rolling_metrics(
    returns: pd.Series,
    windows: list = [20, 252],
    risk_free_rate: float = 0.02,
    annual_factor: int = 252,
    name : str = "returns",
    shift_features: bool = True,  # ✅ 추가

) -> pd.DataFrame:
    """
    주어진 daily return 시리즈에 대해 rolling window 기반 
    Sharpe, Volatility, Sortino, Calmar 계산

    Args:
        returns (pd.Series): 일간 수익률
        windows (list): rolling window list (e.g., [20, 252])
        risk_free_rate (float): 무위험 수익률 (연환산)
        annual_factor (int): 연환산 계수 (default 252)

    Returns:
        pd.DataFrame: 원본 daily_return + 모든 rolling metric columns
    """
    result = pd.DataFrame({'daily_return': returns})
    result["tic"] = name

    for window in windows:
        result[f'sharpe_{window}'] = returns.rolling(window).apply(
            lambda x: em.calculate_sharpe_ratio(x, risk_free_rate, annual_factor),
            raw=False
        )
        result[f'vol_{window}'] = returns.rolling(window).apply(
            lambda x: em.calculate_volatility(x, annual_factor),
            raw=False
        )
        result[f'sortino_{window}'] = returns.rolling(window).apply(
            lambda x: em.calculate_annualized_sortino_ratio(x, risk_free_rate, annual_factor),
            raw=False
        )
        result[f'calmar_{window}'] = returns.rolling(window).apply(
            lambda x: em.calculate_calmar_ratio(x, annual_factor),
            raw=False
        )
    if shift_features:
        feature_cols = [col for col in result.columns if col not in ['daily_return', 'tic']]
        result[feature_cols] = result[feature_cols].shift(1)
        
    return result

In [50]:
rp_eval = calculate_rolling_metrics(rp_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_rp")
minvar_eval = calculate_rolling_metrics(minvar_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_minvar")
ms_eval = calculate_rolling_metrics(ms_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_ms")
paa_eval = calculate_rolling_metrics(paa_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_paa")
equal_eval = calculate_rolling_metrics(equal_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="equal")

In [51]:
ch_rp_eval = calculate_rolling_metrics(ch_rp_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_rp")
ch_minvar_eval = calculate_rolling_metrics(ch_minvar_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_minvar")
ch_ms_eval = calculate_rolling_metrics(ch_ms_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_ms")
ch_paa_eval = calculate_rolling_metrics(ch_paa_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="future_paa")
ch_equal_eval = calculate_rolling_metrics(ch_equal_returns, windows=[20, 252], risk_free_rate=risk_free_rate, annual_factor=annual_factor, name="equal")

In [52]:
risk_df = pd.DataFrame({
    'close' : risk_cum,
    "tic" : "risk_parity"})

minvar_df = pd.DataFrame({
    'close' : minvar_cum,
    "tic" : "minvar"})

ms_df = pd.DataFrame({
    'close' : ms_cum,
    "tic" : "max_sharpe"})

paa_df = pd.DataFrame({
    'close' : paa_cum,
    "tic" : "paa"})

In [53]:
ch_risk_df = pd.DataFrame({
    'close' : ch_risk_cum,
    "tic" : "risk_parity"})

ch_minvar_df = pd.DataFrame({
    'close' : ch_minvar_cum,
    "tic" : "minvar"})

ch_ms_df = pd.DataFrame({
    'close' : ch_ms_cum,
    "tic" : "max_sharpe"})

ch_paa_df = pd.DataFrame({
    'close' : ch_paa_cum,
    "tic" : "paa"})

In [54]:
import pandas as pd

def calculate_momentum_features(df: pd.DataFrame) -> pd.DataFrame:
    """
    주어진 데이터프레임에 대해 모멘텀 관련 특성 생성.
    
    Args:
        df (pd.DataFrame): 종가(close) 컬럼을 포함한 데이터프레임
        close_col (str): 종가 컬럼 이름 (default: 'close')
        
    Returns:
        pd.DataFrame: 모멘텀 특성이 추가된 데이터프레임
    """
    data = df.copy()
    
    # 설정할 period 리스트
    periods = [20, 40, 60, 80, 100, 120, 140, 160, 180, 220, 240, 252]
    columns_list = ["return_1m", "return_3m", "return_6m", "return_12m", "return_avg", "mom_12m", "mom_score"]

    # 기간별 이전 종가 저장
    for idx, period in enumerate(periods):
        col_name = f'close_{idx+1}_month'
        data[col_name] = data['close'].shift(period)
        columns_list.append(col_name)
    
    # 모멘텀 및 수익률 계산
    data['return_1m'] = (data['close'] - data['close_1_month']) / data['close_1_month']
    data['return_3m'] = (data['close'] - data['close_3_month']) / data['close_3_month']
    data['return_6m'] = (data['close'] - data['close_6_month']) / data['close_6_month']
    data['return_12m'] = (data['close'] - data['close_12_month']) / data['close_12_month']
    data['return_avg'] = data[['return_1m', 'return_3m', 'return_6m', 'return_12m']].mean(axis=1)
    data["mom_score"] = (
        12 * data["return_1m"] +
        4 * data["return_3m"] +
        2 * data["return_6m"] +
        1 * data["return_12m"]
    ) / 19

    # 평균 return
    data['return_avg'] = data[['return_1m', 'return_3m', 'return_6m', 'return_12m']].mean(axis=1)
    
    # 모멘텀 점수 (mom_score)
    data['mom_score'] = (
        12 * data['return_1m'] +
        4 * data['return_3m'] +
        2 * data['return_6m'] +
        1 * data['return_12m']
    ) / 19
    
    return data

In [55]:
risk_df = calculate_momentum_features(risk_df)
minvar_df = calculate_momentum_features(minvar_df)
ms_df = calculate_momentum_features(ms_df)
paa_df = calculate_momentum_features(paa_df)

In [56]:
ch_risk_df = calculate_momentum_features(ch_risk_df)
ch_minvar_df = calculate_momentum_features(ch_minvar_df)
ch_ms_df = calculate_momentum_features(ch_ms_df)
ch_paa_df = calculate_momentum_features(ch_paa_df)

In [57]:
risk_df["ret"] = risk_df["close"].pct_change().shift(1)
minvar_df["ret"] = minvar_df["close"].pct_change().shift(1)
ms_df["ret"] = ms_df["close"].pct_change().shift(1)
paa_df["ret"] = paa_df["close"].pct_change().shift(1)

In [58]:
ch_risk_df["ret"] = ch_risk_df["close"].pct_change().shift(1)
ch_minvar_df["ret"] = ch_minvar_df["close"].pct_change().shift(1)
ch_ms_df["ret"] = ch_ms_df["close"].pct_change().shift(1)
ch_paa_df["ret"] = ch_paa_df["close"].pct_change().shift(1)

In [60]:
eval_feature = ['vol_20',
       'sharpe_252', 'vol_252', 'sortino_252', 'calmar_252']

In [61]:
risk_df = pd.concat([risk_df, rp_eval[eval_feature]], axis=1)
minvar_df = pd.concat([minvar_df, minvar_eval[eval_feature]], axis=1)
ms_df = pd.concat([ms_df, ms_eval[eval_feature]], axis=1)
paa_df = pd.concat([paa_df, paa_eval[eval_feature]], axis=1)

In [64]:
ch_risk_df = pd.concat([ch_risk_df, ch_rp_eval[eval_feature]], axis=1)
ch_minvar_df = pd.concat([ch_minvar_df, ch_minvar_eval[eval_feature]], axis=1)
ch_ms_df = pd.concat([ch_ms_df, ch_ms_eval[eval_feature]], axis=1)
ch_paa_df = pd.concat([ch_paa_df, ch_paa_eval[eval_feature]], axis=1)

In [122]:
# portfolio_df = pd.concat([future_risk_df, index_risk_df, future_ms_df, index_ms_df, future_paa_df, index_paa_df], axis=0)

In [65]:
portfolio_df = pd.concat([risk_df, minvar_df, ms_df, paa_df], axis=0)
portfolio_df.reset_index(inplace=True)
portfolio_df.rename(columns={"index": "date"}, inplace=True)

In [66]:
ch_portfolio_df = pd.concat([ch_risk_df, ch_minvar_df, ch_ms_df, ch_paa_df], axis=0)
ch_portfolio_df.reset_index(inplace=True)
ch_portfolio_df.rename(columns={"index": "date"}, inplace=True)

In [70]:
select_features = ['return_1m',
       'return_3m', 'return_6m', 'return_12m', 'return_avg',
       'ret', 'vol_20', 'sharpe_252', 'vol_252', 'sortino_252', 'calmar_252']

In [71]:
for i in portfolio_df.tic.unique():
    imp = portfolio_df[portfolio_df.tic == i].copy()
    print(i)
    print(imp[select_features].describe())

risk_parity
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.005899     0.018057     0.037553     0.081537     0.034739
std       0.043067     0.079119     0.120648     0.181760     0.086054
min      -0.321162    -0.409053    -0.473276    -0.487938    -0.404640
25%      -0.016338    -0.020766    -0.018620    -0.048607    -0.010229
50%       0.009447     0.021836     0.042592     0.090701     0.042823
75%       0.031247     0.065176     0.095901     0.187575     0.085402
max       0.184196     0.427170     0.507004     0.683816     0.271563

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000283     0.118509     1.101099     0.128331     1.270414
std       0.008673     0.068304     1.183478     0.052385     2.131152
min      -0.082540     0.030665    -0.144649     0.056241    -2.502103
25%      -0.003659     0.077450    -0.005763     0.093462    -0.482421
50%       0.000657     0.099788     0.814147     0.110972     1.135118
75%       0.004766     0.135580     1.940583     0.151735     2.664679
max       0.076064     0.647988     5.185520     0.317820     8.541373

        calmar_252
count  5479.000000
mean      1.446350
std       2.351975
min      -1.016501
25%      -0.270709
50%       0.877136
75%       2.204670
max      14.495801
minvar
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.007193     0.021643     0.043921     0.093203     0.040672
std       0.032450     0.058369     0.089798     0.138074     0.065432
min      -0.227152    -0.283409    -0.326315    -0.321864    -0.277075
25%      -0.011301    -0.010259    -0.000880     0.005327     0.003747
50%       0.008598     0.023169     0.041634     0.086003     0.040525
75%       0.027517     0.055740     0.090208     0.184985     0.080199
max       0.131564     0.258909     0.298589     0.524511     0.232538

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000351     0.087344     1.299463     0.093516     1.642486
std       0.006199     0.043191     1.203344     0.032574     2.087952
min      -0.041261     0.025401    -0.064036     0.044379    -2.581443
25%      -0.002727     0.060304     0.047771     0.071203     0.064935
50%       0.000626     0.077450     1.039057     0.085885     1.471694
75%       0.003879     0.101073     2.187135     0.104035     3.101483
max       0.046493     0.395549     4.890530     0.208209     8.588437

        calmar_252
count  5479.000000
mean      1.641876
std       2.220432
min      -1.008882
25%       0.042496
50%       1.116096
75%       2.508754
max      15.556168
max_sharpe
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.004117     0.013088     0.027962     0.057564     0.025237
std       0.053617     0.104937     0.162716     0.245711     0.118649
min      -0.307010    -0.399666    -0.542765    -0.561333    -0.373362
25%      -0.021314    -0.036147    -0.054385    -0.092114    -0.043499
50%       0.005180     0.011924     0.024757     0.052590     0.027310
75%       0.031978     0.066426     0.105172     0.219889     0.097330
max       0.292628     0.498014     0.607415     0.722315     0.484547

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000194     0.147765     0.855437     0.158904     0.764046
std       0.010744     0.083049     1.043725     0.065419     2.071359
min      -0.111067     0.010649    -0.193446     0.060526    -2.983051
25%      -0.004704     0.091638    -0.015133     0.112782    -0.779414
50%       0.000617     0.122620     0.406840     0.147921     0.580535
75%       0.005621     0.178232     1.625290     0.177157     2.316320
max       0.066478     0.577075     4.492821     0.363361     7.307433

        calmar_252
count  5479.000000
mean      1.021370
std       2.015740
min      -1.043661
25%      -0.484101
50%       0.407825
75%       1.831196
max       9.109335
paa
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.005091     0.014565     0.029901     0.059976     0.026926
std       0.060322     0.108105     0.163618     0.237284     0.116859
min      -0.304659    -0.355742    -0.413453    -0.444947    -0.335324
25%      -0.028138    -0.048757    -0.071105    -0.118547    -0.052258
50%       0.004221     0.010199     0.027701     0.048482     0.017476
75%       0.040637     0.073114     0.115792     0.210144     0.099501
max       0.220953     0.455895     0.717839     0.780144     0.426462

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000252     0.181917     0.620188     0.197274     0.456213
std       0.012776     0.087599     0.808753     0.050590     1.589620
min      -0.093081     0.000000    -0.119818     0.092791    -2.440387
25%      -0.006144     0.123903    -0.019651     0.152438    -0.893461
50%       0.000419     0.161196     0.261272     0.199692     0.376411
75%       0.007171     0.220116     1.079164     0.228671     1.541988
max       0.106288     0.815624     3.624358     0.320998     6.091014

        calmar_252
count  5479.000000
mean      0.649470
std       1.433496
min      -1.054667
25%      -0.479895
50%       0.298716
75%       1.408771
max       7.309386

In [73]:
for i in ch_portfolio_df.tic.unique():
    imp = ch_portfolio_df[ch_portfolio_df.tic == i].copy()
    print(i)
    print(imp[select_features].describe())

risk_parity
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.006007     0.018326     0.038120     0.082793     0.035254
std       0.043453     0.078957     0.120304     0.179758     0.085432
min      -0.320986    -0.409064    -0.474793    -0.488784    -0.407426
25%      -0.016347    -0.020946    -0.019106    -0.044034    -0.009731
50%       0.009944     0.023841     0.044241     0.096742     0.045236
75%       0.031599     0.065576     0.100522     0.190017     0.086950
max       0.185379     0.429894     0.523716     0.693679     0.260233

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000290     0.123072     1.074107     0.132824     1.276607
std       0.008977     0.070478     1.133928     0.053737     2.062468
min      -0.087773     0.030663    -0.148380     0.058924    -2.332441
25%      -0.003833     0.081597    -0.005380     0.098579    -0.442287
50%       0.000624     0.104302     0.834318     0.114839     1.165662
75%       0.005035     0.140865     1.848772     0.156305     2.540371
max       0.075291     0.662449     4.833129     0.325614     8.087625

        calmar_252
count  5479.000000
mean      1.427484
std       2.216595
min      -1.022184
25%      -0.246604
50%       0.910783
75%       2.246748
max      12.622320
minvar
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.007604     0.022845     0.046200     0.098286     0.042896
std       0.033148     0.057907     0.087618     0.132088     0.063510
min      -0.217625    -0.274932    -0.317086    -0.325695    -0.266004
25%      -0.011561    -0.009963    -0.002761     0.012770     0.006250
50%       0.008893     0.025761     0.050062     0.105653     0.046047
75%       0.028559     0.058031     0.094106     0.185332     0.084432
max       0.132026     0.257314     0.311994     0.508494     0.206257

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000371     0.094851     1.269572     0.100795     1.683858
std       0.006694     0.046470     1.089828     0.035332     1.976725
min      -0.051008     0.026043    -0.070572     0.044907    -2.618731
25%      -0.003081     0.067534     0.121353     0.078450     0.174223
50%       0.000632     0.084668     1.185247     0.091806     1.712781
75%       0.004136     0.109837     2.081382     0.115188     3.114585
max       0.048475     0.432857     4.605901     0.225830     8.218348

        calmar_252
count  5479.000000
mean      1.632211
std       1.946364
min      -1.052242
25%       0.101246
50%       1.311041
75%       2.700503
max      12.315994
max_sharpe
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.004641     0.014596     0.030766     0.061706     0.027892
std       0.055037     0.107833     0.168570     0.254153     0.122346
min      -0.279729    -0.381242    -0.514015    -0.535033    -0.349399
25%      -0.020892    -0.033319    -0.055562    -0.092036    -0.036096
50%       0.006936     0.018305     0.037430     0.069012     0.034355
75%       0.032894     0.068936     0.114158     0.232167     0.098504
max       0.292628     0.514583     0.612588     0.791329     0.506335

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000224     0.153483     0.908191     0.164892     0.895680
std       0.011265     0.089846     1.048403     0.070875     2.054263
min      -0.121602     0.010649    -0.186620     0.059590    -2.933410
25%      -0.004805     0.094010    -0.015544     0.112482    -0.794379
50%       0.000657     0.125950     0.561124     0.152866     0.815076
75%       0.005718     0.182785     1.653053     0.182455     2.474839
max       0.064333     0.646161     4.847670     0.362755     7.954324

        calmar_252
count  5479.000000
mean      1.138175
std       2.029138
min      -1.017321
25%      -0.479827
50%       0.631435
75%       1.935745
max       9.376527
paa
         return_1m    return_3m    return_6m   return_12m   return_avg  \
count  5711.000000  5671.000000  5611.000000  5479.000000  5711.000000
mean      0.003985     0.011314     0.023593     0.044192     0.020507
std       0.056429     0.100726     0.151132     0.211690     0.106660
min      -0.305385    -0.331677    -0.407480    -0.432151    -0.321356
25%      -0.025757    -0.045032    -0.063638    -0.126158    -0.050002
50%       0.005092     0.015247     0.034982     0.071984     0.023519
75%       0.036241     0.070940     0.111779     0.194660     0.089765
max       0.197201     0.381167     0.598407     0.585989     0.336658

               ret       vol_20   sharpe_252      vol_252  sortino_252  \
count  5729.000000  5711.000000  5479.000000  5479.000000  5479.000000
mean      0.000200     0.171175     0.635613     0.184615     0.528963
std       0.012029     0.082501     0.737057     0.050385     1.566932
min      -0.093081     0.000000    -0.120593     0.087715    -2.437166
25%      -0.005974     0.119385    -0.020021     0.144994    -0.932894
50%       0.000560     0.152173     0.458011     0.177447     0.685778
75%       0.006814     0.204678     1.138854     0.207000     1.671520
max       0.106288     0.815758     3.262609     0.332686     5.265513

        calmar_252
count  5479.000000
mean      0.688674
std       1.367552
min      -1.040645
25%      -0.495585
50%       0.552985
75%       1.464784
max       6.768066

In [75]:
portfolio_df.sort_values(by=["date", "tic"], inplace=True)
portfolio_df.reset_index(drop=True, inplace=True)

In [77]:
ch_portfolio_df.sort_values(by=["date", "tic"], inplace=True)
ch_portfolio_df.reset_index(drop=True, inplace=True)

In [78]:
for i in portfolio_df.tic.unique():
    imp = portfolio_df[portfolio_df.tic == i].copy()
    print(i)
    print(imp.describe())

max_sharpe
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      1.802145       1.800845       1.799749       1.798653
std       0.519045       0.519486       0.520067       0.520654
min       0.980140       0.980140       0.980140       0.980140
25%       1.315708       1.314597       1.313375       1.312376
50%       1.750075       1.749209       1.746387       1.744384
75%       2.239500       2.245856       2.250901       2.254672
max       3.130891       3.130891       3.130891       3.130891

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        1.797489       1.796540       1.795924       1.795261
std         0.521204       0.521881       0.522705       0.523518
min         0.980140       0.980140       0.980140       0.980140
25%         1.311822       1.311431       1.310591       1.308904
50%         1.741659       1.740665       1.738453       1.736765
75%         2.258253       2.261283       2.266212       2.271215
max         3.130891       3.130891       3.130891       3.130891

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        1.794674       1.793998  ...     0.027962     0.057564
std         0.524361       0.525175  ...     0.162716     0.245711
min         0.980140       0.980140  ...    -0.542765    -0.561333
25%         1.307853       1.306823  ...    -0.054385    -0.092114
50%         1.735648       1.734989  ...     0.024757     0.052590
75%         2.273450       2.277648  ...     0.105172     0.219889
max         3.130891       3.130891  ...     0.607415     0.722315

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.025237     0.011123     0.000194     0.147765     0.855437
std       0.118649     0.071690     0.010744     0.083049     1.043725
min      -0.373362    -0.341129    -0.111067     0.010649    -0.193446
25%      -0.043499    -0.024925    -0.004704     0.091638    -0.015133
50%       0.027310     0.012784     0.000617     0.122620     0.406840
75%       0.097330     0.051436     0.005621     0.178232     1.625290
max       0.484547     0.313939     0.066478     0.577075     4.492821

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.158904     0.764046     1.021370
std       0.065419     2.071359     2.015740
min       0.060526    -2.983051    -1.043661
25%       0.112782    -0.779414    -0.484101
50%       0.147921     0.580535     0.407825
75%       0.177157     2.316320     1.831196
max       0.363361     7.307433     9.109335

[8 rows x 25 columns]
minvar
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      3.311943       3.299923       3.287922       3.275525
std       1.384987       1.372402       1.359767       1.346010
min       1.002586       1.002586       1.002586       1.002586
25%       2.208191       2.201342       2.193806       2.186907
50%       3.437570       3.434882       3.433315       3.430464
75%       3.942054       3.923871       3.909594       3.897127
max       6.963843       6.963843       6.963843       6.963843

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        3.263043       3.251452       3.240515       3.229704
std         1.331879       1.319926       1.309473       1.299248
min         1.002586       1.002586       1.002586       1.002586
25%         2.180426       2.177419       2.171065       2.168873
50%         3.428808       3.425941       3.423613       3.421080
75%         3.884556       3.870977       3.862798       3.855828
max         6.663050       6.424384       6.373249       6.370554

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        3.218715       3.208156  ...     0.043921     0.093203
std         1.288541       1.278770  ...     0.089798     0.138074
min         1.002586       1.002586  ...    -0.326315    -0.321864
25%         2.163909       2.157736  ...    -0.000880     0.005327
50%         3.419569       3.417429  ...     0.041634     0.086003
75%         3.850497       3.847035  ...     0.090208     0.184985
max         6.250886       6.202637  ...     0.298589     0.524511

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.040672     0.018522     0.000351     0.087344     1.299463
std       0.065432     0.040359     0.006199     0.043191     1.203344
min      -0.277075    -0.250798    -0.041261     0.025401    -0.064036
25%       0.003747    -0.003021    -0.002727     0.060304     0.047771
50%       0.040525     0.020550     0.000626     0.077450     1.039057
75%       0.080199     0.042474     0.003879     0.101073     2.187135
max       0.232538     0.144539     0.046493     0.395549     4.890530

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.093516     1.642486     1.641876
std       0.032574     2.087952     2.220432
min       0.044379    -2.581443    -1.008882
25%       0.071203     0.064935     0.042496
50%       0.085885     1.471694     1.116096
75%       0.104035     3.101483     2.508754
max       0.208209     8.588437    15.556168

[8 rows x 25 columns]
paa
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      2.215669       2.214496       2.214147       2.213941
std       0.697497       0.698418       0.699607       0.700829
min       0.992380       0.992380       0.992380       0.992380
25%       1.586692       1.575702       1.567206       1.562574
50%       2.241492       2.238291       2.235428       2.231201
75%       2.727219       2.729586       2.731281       2.733391
max       4.458797       4.458797       4.458797       4.458797

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        2.213657       2.213564       2.213851       2.213970
std         0.702050       0.703287       0.704514       0.705762
min         0.992380       0.992380       0.992380       0.992380
25%         1.560403       1.558878       1.555797       1.554116
50%         2.228286       2.227900       2.229826       2.230868
75%         2.734821       2.736560       2.738138       2.740549
max         4.458797       4.458797       4.458797       4.458797

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        2.213993       2.214164  ...     0.029901     0.059976
std         0.707021       0.708278  ...     0.163618     0.237284
min         0.992380       0.992380  ...    -0.413453    -0.444947
25%         1.552525       1.549729  ...    -0.071105    -0.118547
50%         2.232673       2.236832  ...     0.027701     0.048482
75%         2.742715       2.744286  ...     0.115792     0.210144
max         4.458797       4.458797  ...     0.717839     0.780144

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.026926     0.012324     0.000252     0.181917     0.620188
std       0.116859     0.074296     0.012776     0.087599     0.808753
min      -0.335324    -0.316377    -0.093081     0.000000    -0.119818
25%      -0.052258    -0.034055    -0.006144     0.123903    -0.019651
50%       0.017476     0.007777     0.000419     0.161196     0.261272
75%       0.099501     0.056497     0.007171     0.220116     1.079164
max       0.426462     0.276905     0.106288     0.815624     3.624358

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.197274     0.456213     0.649470
std       0.050590     1.589620     1.433496
min       0.092791    -2.440387    -1.054667
25%       0.152438    -0.893461    -0.479895
50%       0.199692     0.376411     0.298716
75%       0.228671     1.541988     1.408771
max       0.320998     6.091014     7.309386

[8 rows x 25 columns]
risk_parity
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      2.630970       2.625757       2.620432       2.614736
std       0.781482       0.777847       0.773996       0.769378
min       0.923240       0.923240       0.923240       0.923240
25%       2.215081       2.210566       2.202093       2.196419
50%       2.764119       2.762418       2.760977       2.758845
75%       3.058552       3.053360       3.048961       3.043887
max       4.353497       4.353497       4.353497       4.353497

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        2.608949       2.603614       2.598592       2.593596
std         0.764539       0.760617       0.757284       0.754003
min         0.923240       0.923240       0.923240       0.923240
25%         2.188516       2.179541       2.174851       2.166690
50%         2.757465       2.755680       2.753616       2.751872
75%         3.038247       3.034893       3.031655       3.025498
max         4.202786       4.157185       4.157185       4.157185

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        2.588190       2.583222  ...     0.037553     0.081537
std         0.749924       0.746676  ...     0.120648     0.181760
min         0.923240       0.923240  ...    -0.473276    -0.487938
25%         2.156255       2.147781  ...    -0.018620    -0.048607
50%         2.749016       2.745898  ...     0.042592     0.090701
75%         3.022533       3.019737  ...     0.095901     0.187575
max         4.070931       4.006583  ...     0.507004     0.683816

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.034739     0.016286     0.000283     0.118509     1.101099
std       0.086054     0.053470     0.008673     0.068304     1.183478
min      -0.404640    -0.358025    -0.082540     0.030665    -0.144649
25%      -0.010229    -0.008176    -0.003659     0.077450    -0.005763
50%       0.042823     0.021699     0.000657     0.099788     0.814147
75%       0.085402     0.048988     0.004766     0.135580     1.940583
max       0.271563     0.199891     0.076064     0.647988     5.185520

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.128331     1.270414     1.446350
std       0.052385     2.131152     2.351975
min       0.056241    -2.502103    -1.016501
25%       0.093462    -0.482421    -0.270709
50%       0.110972     1.135118     0.877136
75%       0.151735     2.664679     2.204670
max       0.317820     8.541373    14.495801

[8 rows x 25 columns]

In [79]:
for i in ch_portfolio_df.tic.unique():
    imp = ch_portfolio_df[ch_portfolio_df.tic == i].copy()
    print(i)
    print(imp.describe())

max_sharpe
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      2.229427       2.228442       2.227744       2.227186
std       0.619143       0.620001       0.620975       0.621996
min       0.993479       0.993479       0.993479       0.993479
25%       1.654808       1.653260       1.650207       1.648992
50%       2.271037       2.269894       2.268405       2.267178
75%       2.676998       2.682551       2.684908       2.689220
max       3.758767       3.758767       3.758767       3.758767

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        2.226729       2.226435       2.226447       2.226347
std         0.623047       0.624129       0.625236       0.626346
min         0.993479       0.993479       0.993479       0.993479
25%         1.648332       1.646258       1.645799       1.644494
50%         2.265759       2.264967       2.265861       2.266537
75%         2.693414       2.697083       2.703923       2.707905
max         3.758767       3.758767       3.758767       3.758767

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        2.226356       2.226275  ...     0.030766     0.061706
std         0.627464       0.628584  ...     0.168570     0.254153
min         0.993479       0.993479  ...    -0.514015    -0.535033
25%         1.642469       1.640805  ...    -0.055562    -0.092036
50%         2.267362       2.267449  ...     0.037430     0.069012
75%         2.712748       2.716291  ...     0.114158     0.232167
max         3.758767       3.758767  ...     0.612588     0.791329

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.027892     0.011485     0.000224     0.153483     0.908191
std       0.122346     0.073526     0.011265     0.089846     1.048403
min      -0.349399    -0.308402    -0.121602     0.010649    -0.186620
25%      -0.036096    -0.020846    -0.004805     0.094010    -0.015544
50%       0.034355     0.014431     0.000657     0.125950     0.561124
75%       0.098504     0.050859     0.005718     0.182785     1.653053
max       0.506335     0.319785     0.064333     0.646161     4.847670

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.164892     0.895680     1.138175
std       0.070875     2.054263     2.029138
min       0.059590    -2.933410    -1.017321
25%       0.112482    -0.794379    -0.479827
50%       0.152866     0.815076     0.631435
75%       0.182455     2.474839     1.935745
max       0.362755     7.954324     9.376527

[8 rows x 25 columns]
minvar
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      3.283127       3.268187       3.253094       3.237688
std       1.472205       1.452920       1.432944       1.411741
min       0.999251       0.999251       0.999251       0.999251
25%       2.214273       2.212140       2.208976       2.204999
50%       3.198502       3.195284       3.190473       3.186895
75%       3.759539       3.748025       3.737675       3.728009
max       7.695312       7.687810       7.687810       7.687810

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        3.222535       3.208120       3.194018       3.179844
std         1.390999       1.372222       1.354122       1.335595
min         0.999251       0.999251       0.999251       0.999251
25%         2.202623       2.200014       2.196312       2.192338
50%         3.185217       3.181786       3.178291       3.172594
75%         3.713753       3.706871       3.697041       3.685418
max         7.428692       7.373223       7.301623       7.172324

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        3.165798       3.152094  ...     0.046200     0.098286
std         1.317216       1.299605  ...     0.087618     0.132088
min         0.999251       0.999251  ...    -0.317086    -0.325695
25%         2.184623       2.182223  ...    -0.002761     0.012770
50%         3.168736       3.167403  ...     0.050062     0.105653
75%         3.678408       3.670689  ...     0.094106     0.185332
max         7.127646       7.127646  ...     0.311994     0.508494

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.042896     0.019436     0.000371     0.094851     1.269572
std       0.063510     0.039972     0.006694     0.046470     1.089828
min      -0.266004    -0.239078    -0.051008     0.026043    -0.070572
25%       0.006250    -0.001886    -0.003081     0.067534     0.121353
50%       0.046047     0.022703     0.000632     0.084668     1.185247
75%       0.084432     0.043695     0.004136     0.109837     2.081382
max       0.206257     0.147239     0.048475     0.432857     4.605901

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.100795     1.683858     1.632211
std       0.035332     1.976725     1.946364
min       0.044907    -2.618731    -1.052242
25%       0.078450     0.174223     0.101246
50%       0.091806     1.712781     1.311041
75%       0.115188     3.114585     2.700503
max       0.225830     8.218348    12.315994

[8 rows x 25 columns]
paa
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      2.110200       2.110571       2.111636       2.112973
std       0.595400       0.596397       0.597159       0.597786
min       0.974624       0.974624       0.974624       0.974624
25%       1.559946       1.559227       1.558249       1.557764
50%       2.216922       2.221550       2.226446       2.229593
75%       2.519247       2.520601       2.521473       2.523445
max       3.785614       3.785614       3.785614       3.785614

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        2.114229       2.115506       2.117092       2.118621
std         0.598468       0.599141       0.599613       0.600132
min         0.974624       0.974624       0.974624       0.974624
25%         1.557404       1.555953       1.554989       1.554448
50%         2.232771       2.237210       2.239332       2.242257
75%         2.523880       2.525361       2.527957       2.529683
max         3.785614       3.785614       3.785614       3.785614

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        2.120118       2.121665  ...     0.023593     0.044192
std         0.600683       0.601204  ...     0.151132     0.211690
min         0.974624       0.974624  ...    -0.407480    -0.432151
25%         1.553153       1.552439  ...    -0.063638    -0.126158
50%         2.244890       2.247736  ...     0.034982     0.071984
75%         2.530425       2.531791  ...     0.111779     0.194660
max         3.785614       3.785614  ...     0.598407     0.585989

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.020507     0.009012     0.000200     0.171175     0.635613
std       0.106660     0.068991     0.012029     0.082501     0.737057
min      -0.321356    -0.310193    -0.093081     0.000000    -0.120593
25%      -0.050002    -0.030754    -0.005974     0.119385    -0.020021
50%       0.023519     0.008784     0.000560     0.152173     0.458011
75%       0.089765     0.050279     0.006814     0.204678     1.138854
max       0.336658     0.250257     0.106288     0.815758     3.262609

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.184615     0.528963     0.688674
std       0.050385     1.566932     1.367552
min       0.087715    -2.437166    -1.040645
25%       0.144994    -0.932894    -0.495585
50%       0.177447     0.685778     0.552985
75%       0.207000     1.671520     1.464784
max       0.332686     5.265513     6.768066

[8 rows x 25 columns]
risk_parity
             close  close_1_month  close_2_month  close_3_month  \
count  5731.000000    5711.000000    5691.000000    5671.000000
mean      2.635002       2.629423       2.623713       2.617641
std       0.797469       0.793248       0.788755       0.783475
min       0.907053       0.907053       0.907053       0.907053
25%       2.215845       2.209831       2.205557       2.199663
50%       2.724923       2.723024       2.721225       2.718803
75%       3.050630       3.047452       3.044614       3.040424
max       4.458488       4.458488       4.458488       4.458488

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    5651.000000    5631.000000    5611.000000    5591.000000
mean        2.611498       2.605779       2.600357       2.594936
std         0.777999       0.773415       0.769417       0.765420
min         0.907053       0.907053       0.907053       0.907053
25%         2.196303       2.189322       2.180020       2.173181
50%         2.716287       2.714661       2.713960       2.711896
75%         3.037458       3.035155       3.033165       3.030236
max         4.315381       4.260979       4.260979       4.260979

       close_8_month  close_9_month  ...    return_6m   return_12m  \
count    5571.000000    5551.000000  ...  5611.000000  5479.000000
mean        2.589130       2.583785  ...     0.038120     0.082793
std         0.760620       0.756740  ...     0.120304     0.179758
min         0.907053       0.907053  ...    -0.474793    -0.488784
25%         2.165005       2.161911  ...    -0.019106    -0.044034
50%         2.709870       2.706802  ...     0.044241     0.096742
75%         3.025946       3.022575  ...     0.100522     0.190017
max         4.184198       4.119817  ...     0.523716     0.693679

        return_avg    mom_score          ret       vol_20   sharpe_252  \
count  5711.000000  5479.000000  5729.000000  5711.000000  5479.000000
mean      0.035254     0.016556     0.000290     0.123072     1.074107
std       0.085432     0.053341     0.008977     0.070478     1.133928
min      -0.407426    -0.357670    -0.087773     0.030663    -0.148380
25%      -0.009731    -0.007479    -0.003833     0.081597    -0.005380
50%       0.045236     0.023191     0.000624     0.104302     0.834318
75%       0.086950     0.048655     0.005035     0.140865     1.848772
max       0.260233     0.198748     0.075291     0.662449     4.833129

           vol_252  sortino_252   calmar_252
count  5479.000000  5479.000000  5479.000000
mean      0.132824     1.276607     1.427484
std       0.053737     2.062468     2.216595
min       0.058924    -2.332441    -1.022184
25%       0.098579    -0.442287    -0.246604
50%       0.114839     1.165662     0.910783
75%       0.156305     2.540371     2.246748
max       0.325614     8.087625    12.622320

[8 rows x 25 columns]

In [80]:
for i in portfolio_df.tic.unique():
    imp = portfolio_df[portfolio_df.tic == i].copy()
    print(i)
    print(imp.isna().sum())

max_sharpe
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
minvar
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
paa
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
risk_parity
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64

In [81]:
for i in ch_portfolio_df.tic.unique():
    imp = ch_portfolio_df[ch_portfolio_df.tic == i].copy()
    print(i)
    print(imp.isna().sum())

max_sharpe
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
minvar
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
paa
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64
risk_parity
date                0
close               0
tic                 0
close_1_month      20
close_2_month      40
close_3_month      60
close_4_month      80
close_5_month     100
close_6_month     120
close_7_month     140
close_8_month     160
close_9_month     180
close_10_month    220
close_11_month    240
close_12_month    252
return_1m          20
return_3m          60
return_6m         120
return_12m        252
return_avg         20
mom_score         252
ret                 2
vol_20             20
sharpe_252        252
vol_252           252
sortino_252       252
calmar_252        252
dtype: int64

In [82]:
portfolio_na = portfolio_df.dropna()

In [83]:
ch_portfolio_na = ch_portfolio_df.dropna()

In [84]:
portfolio_na.reset_index(drop=True, inplace=True)

In [85]:
ch_portfolio_na.reset_index(drop=True, inplace=True)

In [86]:
for tic  in portfolio_na.tic.unique():
    imp = portfolio_na[portfolio_na.tic == tic].copy()
    print(tic)
    print(imp.date.min())
    print(imp.date.max())

max_sharpe
2003-02-19
2024-12-31
minvar
2003-02-19
2024-12-31
paa
2003-02-19
2024-12-31
risk_parity
2003-02-19
2024-12-31

In [87]:
for tic  in ch_portfolio_na.tic.unique():
    imp = ch_portfolio_na[ch_portfolio_na.tic == tic].copy()
    print(tic)
    print(imp.date.min())
    print(imp.date.max())

max_sharpe
2003-02-19
2024-12-31
minvar
2003-02-19
2024-12-31
paa
2003-02-19
2024-12-31
risk_parity
2003-02-19
2024-12-31

In [88]:
portfolio_na.rename(columns={"tic": "ticker"}, inplace=True)

/tmp/ipykernel_237390/1574858568.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  portfolio_na.rename(columns={"tic": "ticker"}, inplace=True)

In [89]:
ch_portfolio_na.rename(columns={"tic": "ticker"}, inplace=True)

/tmp/ipykernel_237390/1223831586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ch_portfolio_na.rename(columns={"tic": "ticker"}, inplace=True)

In [90]:
TRAIN_START_DATE = '2003-01-01'
TRAIN_END_DATE = '2013-12-31'
VAILD_START_DATE = '2014-01-01'
VAILD_END_DATE = '2018-12-31'
TEST_START_DATE = '2019-01-01'
TEST_END_DATE = '2024-12-31'

In [91]:
def data_split(df, start, end, target_date_col="date"):
    """
    split the dataset into training or testing using date
    :param data: (df) pandas dataframe, start, end
    :return: (df) pandas dataframe
    """
    data = df[(df[target_date_col] >= start) & (df[target_date_col] <= end)]
    data = data.sort_values([target_date_col, "ticker"], ignore_index=True)
    # data.index = data[target_date_col].factorize()[0]
    return data

In [92]:
train = data_split(portfolio_na, TRAIN_START_DATE,TRAIN_END_DATE)
vaild = data_split(portfolio_na, VAILD_START_DATE,VAILD_END_DATE)
test = data_split(ch_portfolio_na, TEST_START_DATE,TEST_END_DATE)

In [141]:
# def min_max_normalize_by_ticker_train_test(train_df, vaild_df, test_df, columns):
#     """
#     주어진 컬럼들을 train 기준으로 티커별 min-max 정규화
    
#     Parameters:
#         train_df (DataFrame): 학습용 데이터
#         test_df (DataFrame): 테스트용 데이터
#         columns (list): 정규화할 컬럼 리스트
        
#     Returns:
#         train_df, test_df: 정규화된 결과가 포함된 데이터프레임
#     """
#     # 티커별로 정규화 통계 계산
#     stats = train_df.groupby("ticker")[columns].agg(["min", "max"])
    
#     # 컬럼명 정리 (MultiIndex → flat column name)
#     stats.columns = [f"{col}_{stat}" for col, stat in stats.columns]

#     # train/test에 붙이기
#     train_df = train_df.merge(stats, on="ticker", how="left")
#     vaild_df = vaild_df.merge(stats, on="ticker", how="left")
#     test_df = test_df.merge(stats, on="ticker", how="left")

#     # 컬럼별 정규화 수행
#     for col in columns:
#         min_col = f"{col}_min"
#         max_col = f"{col}_max"
#         norm_col = f"{col}_norm"

#         train_df[norm_col] = (train_df[col] - train_df[min_col]) / (train_df[max_col] - train_df[min_col])
#         vaild_df[norm_col] = (vaild_df[col] - vaild_df[min_col]) / (vaild_df[max_col] - vaild_df[min_col])
#         test_df[norm_col] = (test_df[col] - test_df[min_col]) / (test_df[max_col] - test_df[min_col])

#     # 불필요한 min/max 컬럼 제거
#     cols_to_drop = [f"{col}_min" for col in columns] + [f"{col}_max" for col in columns]
#     train_df.drop(columns=cols_to_drop, inplace=True)
#     vaild_df.drop(columns=cols_to_drop, inplace=True)
#     test_df.drop(columns=cols_to_drop, inplace=True)

#     return train_df, vaild_df, test_df

In [97]:
def min_max_normalize_global_train_test(train_df, valid_df, test_df, columns):
    """
    전체 train 데이터 기준으로 주어진 컬럼들에 대해 min-max 정규화
    
    Parameters:
        train_df (DataFrame): 학습용 데이터
        valid_df (DataFrame): 검증용 데이터
        test_df (DataFrame): 테스트용 데이터
        columns (list): 정규화할 컬럼 리스트
        
    Returns:
        train_df, valid_df, test_df: 정규화된 결과가 포함된 데이터프레임
    """
    # train 데이터 전체 기준으로 min/max 계산
    stats = train_df[columns].agg(["min", "max"])
    
    for col in columns:
        min_val = stats.loc["min", col]
        max_val = stats.loc["max", col]
        norm_col = f"{col}_norm"
        
        train_df[norm_col] = (train_df[col] - min_val) / (max_val - min_val)
        valid_df[norm_col] = (valid_df[col] - min_val) / (max_val - min_val)
        test_df[norm_col] = (test_df[col] - min_val) / (max_val - min_val)
    
    return train_df, valid_df, test_df

In [98]:
columns_to_normalize = ["ret", 'close', 'return_1m', 'return_3m',
       'return_6m', 'return_12m', 'return_avg', 'mom_score',  'vol_20',
       'sharpe_252', 'vol_252', 'sortino_252', 'calmar_252']

In [99]:
# train_df, vaild_df, test_df = min_max_normalize_by_ticker_train_test(train, vaild, test, columns_to_normalize)

In [100]:
train_df, vaild_df, test_df = min_max_normalize_global_train_test(train, vaild, test, columns_to_normalize)

In [101]:
train_df[['ret_norm',
       'close_norm', 'return_1m_norm', 'return_3m_norm', 'return_6m_norm',
       'return_12m_norm', 'return_avg_norm', 'mom_score_norm', 'vol_20_norm',
       'sharpe_252_norm', 'vol_252_norm', 'sortino_252_norm']].describe()

,ret_norm,close_norm,return_1m_norm,return_3m_norm,return_6m_norm,return_12m_norm,return_avg_norm,mom_score_norm,vol_20_norm,sharpe_252_norm,vol_252_norm,sortino_252_norm
count,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000,10872.000000
mean,0.500879,0.368422,0.537376,0.481466,0.476134,0.507985,0.551218,0.581322,0.224698,0.264507,0.321069,0.363120
std,0.062473,0.201607,0.085573,0.108571,0.119920,0.153075,0.123860,0.099116,0.129240,0.207574,0.217429,0.178900
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.473055,0.192090,0.494903,0.427050,0.421348,0.429270,0.488905,0.534055,0.132762,0.053640,0.153973,0.231908
50%,0.503625,0.390211,0.543753,0.483416,0.473752,0.522179,0.557823,0.585431,0.189331,0.233141,0.269997,0.354328
75%,0.532286,0.513417,0.585922,0.541398,0.542365,0.604102,0.631833,0.639796,0.279838,0.418875,0.466530,0.486833
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [102]:
for tic in test_df.ticker.unique():
    imp = train_df[train_df.ticker == tic].copy()
    print(tic)
    print(imp.describe())

max_sharpe
             close  close_1_month  close_2_month  close_3_month  \
count  2718.000000    2718.000000    2718.000000    2718.000000
mean      1.966360       1.955953       1.945259       1.934425
std       0.526150       0.528247       0.530788       0.533768
min       1.013740       1.013740       1.013740       1.013740
25%       1.483544       1.474339       1.466626       1.460190
50%       1.991601       1.985068       1.972635       1.967868
75%       2.423118       2.414747       2.408939       2.403097
max       3.130891       3.130891       3.130891       3.130891

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    2718.000000    2718.000000    2718.000000    2718.000000
mean        1.923839       1.913943       1.903629       1.893545
std         0.536731       0.539361       0.541481       0.544166
min         1.013740       1.013740       1.013740       1.013740
25%         1.452585       1.444001       1.434101       1.422474
50%         1.958075       1.947586       1.929414       1.920683
75%         2.397060       2.391666       2.385467       2.381793
max         3.130891       3.130891       3.130891       3.130891

       close_8_month  close_9_month  ...  return_3m_norm  return_6m_norm  \
count    2718.000000    2718.000000  ...     2718.000000     2718.000000
mean        1.882676       1.871738  ...        0.478724        0.472212
std         0.545882       0.547057  ...        0.123835        0.135417
min         1.013740       1.013740  ...        0.010348        0.000000
25%         1.406202       1.378972  ...        0.412875        0.401166
50%         1.911954       1.903120  ...        0.480291        0.464746
75%         2.368079       2.358210  ...        0.550678        0.550361
max         3.130891       3.130891  ...        1.000000        0.912404

       return_12m_norm  return_avg_norm  mom_score_norm  vol_20_norm  \
count      2718.000000      2718.000000     2718.000000  2718.000000
mean          0.499408         0.545212        0.577821     0.248233
std           0.165597         0.137273        0.110911     0.136534
min           0.000000         0.037635        0.025732     0.080154
25%           0.424517         0.476103        0.523090     0.153623
50%           0.520339         0.557209        0.581735     0.196770
75%           0.604308         0.631754        0.643422     0.309306
max           0.872969         0.958911        1.000000     0.738768

       sharpe_252_norm  vol_252_norm  sortino_252_norm  calmar_252_norm
count      2718.000000   2718.000000       2718.000000      2718.000000
mean          0.231318      0.367421          0.338643         0.135706
std           0.175325      0.236782          0.157226         0.089368
min           0.000000      0.119587          0.000000         0.002140
25%           0.047081      0.192208          0.226852         0.068584
50%           0.214575      0.294172          0.341592         0.129418
75%           0.370508      0.438052          0.458889         0.186336
max           0.742434      1.000000          0.721699         0.507821

[8 rows x 38 columns]
minvar
             close  close_1_month  close_2_month  close_3_month  \
count  2718.000000    2718.000000    2718.000000    2718.000000
mean      2.402243       2.384282       2.366276       2.347856
std       0.779981       0.780276       0.780846       0.781224
min       1.093820       1.093820       1.093820       1.079695
25%       1.676499       1.665405       1.656687       1.647343
50%       2.375763       2.366167       2.350578       2.333038
75%       3.262096       3.246023       3.215385       3.185899
max       3.747747       3.747747       3.747747       3.747747

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    2718.000000    2718.000000    2718.000000    2718.000000
mean        2.329777       2.312064       2.293947       2.275905
std         0.781906       0.783178       0.782894       0.782756
min         1.066908       1.045443       1.045443       1.045443
25%         1.628428       1.604906       1.583889       1.573386
50%         2.308657       2.292178       2.280738       2.257229
75%         3.156700       3.134533       3.084728       2.952533
max         3.747747       3.747747       3.747747       3.747747

       close_8_month  close_9_month  ...  return_3m_norm  return_6m_norm  \
count    2718.000000    2718.000000  ...     2718.000000     2718.000000
mean        2.256955       2.238327  ...        0.481883        0.476719
std         0.780172       0.777390  ...        0.070895        0.079300
min         1.045443       1.045443  ...        0.138516        0.171703
25%         1.567810       1.561834  ...        0.449444        0.441351
50%         2.237375       2.205411  ...        0.482394        0.473486
75%         2.800677       2.772129  ...        0.524025        0.519218
max         3.740976       3.618136  ...        0.736398        0.667421

       return_12m_norm  return_avg_norm  mom_score_norm  vol_20_norm  \
count      2718.000000      2718.000000     2718.000000  2718.000000
mean          0.513103         0.553721        0.582439     0.150871
std           0.111738         0.086708        0.066932     0.077270
min           0.178511         0.153489        0.163305     0.059928
25%           0.452553         0.513006        0.550954     0.100078
50%           0.517503         0.553826        0.585160     0.131790
75%           0.587463         0.611499        0.623129     0.179439
max           0.804015         0.766666        0.765399     0.610426

       sharpe_252_norm  vol_252_norm  sortino_252_norm  calmar_252_norm
count      2718.000000   2718.000000       2718.000000      2718.000000
mean          0.338816      0.150122          0.421672         0.192481
std           0.226003      0.124341          0.187399         0.138127
min           0.024059      0.000000          0.015176         0.006102
25%           0.130069      0.057976          0.282723         0.093629
50%           0.355856      0.105011          0.442172         0.185750
75%           0.505981      0.215511          0.543266         0.245590
max           0.945159      0.492211          1.000000         1.000000

[8 rows x 38 columns]
paa
             close  close_1_month  close_2_month  close_3_month  \
count  2718.000000    2718.000000    2718.000000    2718.000000
mean      2.431384       2.418177       2.404397       2.390295
std       0.782233       0.788197       0.794987       0.801966
min       1.056447       1.056447       1.056447       1.015483
25%       1.767048       1.714151       1.666166       1.604418
50%       2.578469       2.561607       2.538843       2.522226
75%       2.928912       2.922082       2.913946       2.907711
max       4.458797       4.458797       4.458797       4.458797

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    2718.000000    2718.000000    2718.000000    2718.000000
mean        2.376925       2.364386       2.351618       2.339272
std         0.809166       0.815666       0.821824       0.828535
min         1.008578       1.008578       1.008578       1.008578
25%         1.504039       1.473720       1.456870       1.446713
50%         2.502925       2.486054       2.466288       2.438525
75%         2.907711       2.907711       2.907711       2.907711
max         4.458797       4.458797       4.458797       4.458797

       close_8_month  close_9_month  ...  return_3m_norm  return_6m_norm  \
count    2718.000000    2718.000000  ...     2718.000000     2718.000000
mean        2.326107       2.312826  ...        0.482892        0.477734
std         0.834673       0.840728  ...        0.130072        0.143333
min         1.008578       1.008578  ...        0.058772        0.102579
25%         1.438470       1.431832  ...        0.398741        0.385867
50%         2.418876       2.405441  ...        0.477761        0.471472
75%         2.907081       2.907081  ...        0.561393        0.564802
max         4.458797       4.458797  ...        0.953566        1.000000

       return_12m_norm  return_avg_norm  mom_score_norm  vol_20_norm  \
count      2718.000000      2718.000000     2718.000000  2718.000000
mean          0.508352         0.552443        0.582361     0.296014
std           0.173745         0.144832        0.118759     0.126721
min           0.107372         0.189961        0.204255     0.000000
25%           0.383261         0.445755        0.505173     0.209409
50%           0.504254         0.543883        0.574590     0.270807
75%           0.629986         0.656324        0.659575     0.359554
max           1.000000         1.000000        0.966991     0.826822

       sharpe_252_norm  vol_252_norm  sortino_252_norm  calmar_252_norm
count      2718.000000   2718.000000       2718.000000      2718.000000
mean          0.185319      0.489436          0.300199         0.120792
std           0.158462      0.127820          0.140286         0.085594
min           0.015717      0.226961          0.044869         0.000000
25%           0.034654      0.411785          0.182498         0.049394
50%           0.148459      0.501382          0.298123         0.106523
75%           0.300775      0.565588          0.395424         0.176356
max           0.709765      0.755075          0.773199         0.523829

[8 rows x 38 columns]
risk_parity
             close  close_1_month  close_2_month  close_3_month  \
count  2718.000000    2718.000000    2718.000000    2718.000000
mean      2.219841       2.205458       2.190995       2.176367
std       0.587928       0.593225       0.598077       0.602759
min       0.969376       0.969376       0.969376       0.969376
25%       1.681112       1.665473       1.655828       1.646985
50%       2.364405       2.355349       2.340865       2.330344
75%       2.742326       2.732882       2.726981       2.720625
max       3.191592       3.191592       3.191592       3.191592

       close_4_month  close_5_month  close_6_month  close_7_month  \
count    2718.000000    2718.000000    2718.000000    2718.000000
mean        2.162039       2.147985       2.134377       2.121186
std         0.607845       0.613668       0.618467       0.623657
min         0.967732       0.923240       0.923240       0.923240
25%         1.639091       1.631418       1.626041       1.619539
50%         2.320691       2.306947       2.285550       2.263819
75%         2.713751       2.707162       2.698449       2.690277
max         3.191592       3.191592       3.191592       3.191592

       close_8_month  close_9_month  ...  return_3m_norm  return_6m_norm  \
count    2718.000000    2718.000000  ...     2718.000000     2718.000000
mean        2.107394       2.093783  ...        0.482366        0.477871
std         0.626763       0.629142  ...        0.099364        0.111119
min         0.923240       0.923240  ...        0.000000        0.055124
25%         1.611550       1.602532  ...        0.435613        0.437045
50%         2.235658       2.216403  ...        0.492073        0.485136
75%         2.679290       2.666055  ...        0.542561        0.542357
max         3.191592       3.191592  ...        0.921897        0.832751

       return_12m_norm  return_avg_norm  mom_score_norm  vol_20_norm  \
count      2718.000000      2718.000000     2718.000000  2718.000000
mean          0.511078         0.553495        0.582667     0.203675
std           0.153458         0.118300        0.091684     0.120927
min           0.054712         0.000000        0.000000     0.070296
25%           0.445696         0.512616        0.548792     0.123017
50%           0.538647         0.569925        0.597983     0.169650
75%           0.609131         0.630521        0.638032     0.246161
max           0.928192         0.800151        0.849700     1.000000

       sharpe_252_norm  vol_252_norm  sortino_252_norm  calmar_252_norm
count      2718.000000   2718.000000       2718.000000      2718.000000
mean          0.302577      0.277296          0.391965         0.177030
std           0.226099      0.199077          0.199289         0.143688
min           0.009072      0.061371          0.017519         0.001402
25%           0.087406      0.143299          0.256725         0.081353
50%           0.298429      0.187919          0.395928         0.155463
75%           0.459189      0.348649          0.508057         0.235452
max           1.000000      0.850952          0.995726         0.975131

[8 rows x 38 columns]

In [103]:
# train_df.to_csv("../data/portfolio_price/train_total_asset_portfolio_monthly_v1.csv", index=False)
# vaild_df.to_csv("../data/portfolio_price/vaild_total_asset_portfolio_monthly_v1.csv", index=False)
test_df.to_csv("../data/portfolio_price/test_total_asset_portfolio_monthly_v2_remove.csv", index=False)

In [104]:
train_df.columns

Index(['date', 'close', 'ticker', 'close_1_month', 'close_2_month',
       'close_3_month', 'close_4_month', 'close_5_month', 'close_6_month',
       'close_7_month', 'close_8_month', 'close_9_month', 'close_10_month',
       'close_11_month', 'close_12_month', 'return_1m', 'return_3m',
       'return_6m', 'return_12m', 'return_avg', 'mom_score', 'ret', 'vol_20',
       'sharpe_252', 'vol_252', 'sortino_252', 'calmar_252', 'ret_norm',
       'close_norm', 'return_1m_norm', 'return_3m_norm', 'return_6m_norm',
       'return_12m_norm', 'return_avg_norm', 'mom_score_norm', 'vol_20_norm',
       'sharpe_252_norm', 'vol_252_norm', 'sortino_252_norm',
       'calmar_252_norm'],
      dtype='object')

In [105]:
select_features = ['ret_norm',
       'close_norm', 'return_1m_norm', 'return_3m_norm', 'return_6m_norm',
       'return_12m_norm', 'return_avg_norm', 'mom_score_norm', 'vol_20_norm',
       'sharpe_252_norm', 'vol_252_norm', 'sortino_252_norm',
       'calmar_252_norm']

In [106]:
tot_data = pd.concat([train_df, vaild_df, test_df])

In [107]:
tot_data = tot_data.sort_values(["date", "ticker"])

In [108]:
describe_df = tot_data[select_features].describe(include='all')

In [109]:
describe_df = vaild_df[select_features].describe(include='all')

In [110]:
# 고유 날짜/종목 추출 및 정렬
dates = np.sort(tot_data['date'].unique())
tics = np.sort(tot_data['ticker'].unique())

In [111]:
# 인덱스 매핑 (빠른 접근용)
date2idx = {d: i for i, d in enumerate(dates)}
tic2idx = {t: i for i, t in enumerate(tics)}

In [112]:
state_array = np.zeros((len(dates), len(tics), len(select_features)), dtype=np.float32)

In [113]:
for row in tot_data.itertuples():
    d_idx = date2idx[row.date]
    t_idx = tic2idx[row.ticker]
    f_vals = [getattr(row, f) for f in select_features]
    state_array[d_idx, t_idx, :] = np.nan_to_num(f_vals)  # NaN은 0으로

In [114]:
state_array[0]

array([[0.52454066, 0.05266879, 0.56561184, 0.57070166, 0.47606272,
        0.53918004, 0.5933397 , 0.62728447, 0.17319444, 0.29534742,
        0.15763204, 0.39856285, 0.19112083],
       [0.5052916 , 0.04988786, 0.5095343 , 0.5160665 , 0.47956786,
        0.51940084, 0.5614266 , 0.5768683 , 0.11008433, 0.39448565,
        0.05420408, 0.4710987 , 0.21094742],
       [0.6100688 , 0.08173236, 0.7072097 , 0.7105302 , 0.5550068 ,
        0.6090118 , 0.71574944, 0.7750132 , 0.3540435 , 0.31797665,
        0.31493944, 0.4333538 , 0.21528666],
       [0.5231913 , 0.01237122, 0.49219704, 0.4831367 , 0.43249178,
        0.4311548 , 0.49578023, 0.53805256, 0.12383573, 0.04260106,
        0.18323201, 0.22483054, 0.06648669]], dtype=float32)

In [115]:
tot_data[tot_data["date"]=="2018-12-31"][select_features]

,ret_norm,close_norm,return_1m_norm,return_3m_norm,return_6m_norm,return_12m_norm,return_avg_norm,mom_score_norm,vol_20_norm,sharpe_252_norm,vol_252_norm,sortino_252_norm,calmar_252_norm
5000,0.299215,0.072382,0.307433,0.126032,0.187754,0.160631,0.162264,0.246562,0.531914,0.026580,0.318634,0.000691,0.009884
5001,0.512827,0.787025,0.530154,0.418733,0.413576,0.381687,0.458082,0.532590,0.148906,0.035301,0.063629,0.148806,0.041576
5002,-0.048415,0.169143,0.149386,0.099472,0.151944,0.156371,0.110539,0.137832,1.258701,0.018160,0.715715,0.095178,0.011490
5003,0.559344,0.498949,0.471368,0.338436,0.348587,0.323406,0.377157,0.455129,0.245459,0.033479,0.147682,0.071094,0.024079

In [116]:
TRAIN_START_DATE = '2003-01-01'
TRAIN_END_DATE = '2013-12-31'
VAILD_START_DATE = '2014-01-01'
VAILD_END_DATE = '2018-12-31'
TEST_START_DATE = '2019-01-01'
TEST_END_DATE = '2024-12-31'

In [117]:
valid_start_date = "2011-01-03"
test_start_date = "2017-01-03"

In [118]:
date2idx['2014-01-02']

2718

In [119]:
train = state_array[:2718]

In [120]:
valid = state_array[2718:3969]

In [121]:
test = state_array[3969:]

In [122]:
import torch

In [123]:
train_tensor = torch.from_numpy(train)
valid_tensor = torch.from_numpy(valid)
test_tensor = torch.from_numpy(test)

In [124]:
train.shape

(2718, 4, 13)

In [125]:
train_tensor.shape

torch.Size([2718, 4, 13])

In [126]:
valid_tensor.shape

torch.Size([1251, 4, 13])

In [127]:
# torch.save(train_tensor, "../data/portfolio_price/concat_portfolio_train_monthly_v1.pt")
torch.save(test_tensor,  "../data/portfolio_price/concat_portfolio_test_monthly_v2_remove.pt")
# torch.save(valid_tensor, "../data/portfolio_price/concat_portfolio_valid_monthly_v1.pt")

In [128]:
def calculate_annual_return(returns, annual_factor=252):
    returns = np.array(returns, dtype=np.float64)
    cumulative = np.prod(1 + returns)
    n_periods = len(returns)
    return cumulative ** (annual_factor / n_periods) - 1


def calculate_max_drawdown(returns):
    returns = np.array(returns, dtype=np.float64)
    cumulative_returns = np.cumprod(1 + returns)
    running_max = np.maximum.accumulate(cumulative_returns)
    drawdowns = (cumulative_returns - running_max) / running_max
    return abs(np.min(drawdowns))

def calculate_volatility(returns, annual_factor=252):
    returns = np.asarray(returns)
    return np.std(returns, ddof=1) * np.sqrt(annual_factor)

def calculate_sharpe_ratio(returns, risk_free_rate=0.02, annual_factor=252):
    returns = np.array(returns, dtype=np.float64)
    annual_return = calculate_annual_return(returns, annual_factor)
    annual_std_dev = calculate_volatility(returns, annual_factor)
    excess_return =  (annual_return - risk_free_rate) 
    # 연환산 수익률과 표준편차
    return excess_return / annual_std_dev if annual_std_dev != 0 else 0.0


def calculate_cumulative_return(returns):
    returns = np.array(returns, dtype=np.float64)
    return np.prod(1 + returns) - 1

def calculate_volatility(returns, annual_factor=252):
    returns = np.asarray(returns)
    return np.std(returns, ddof=1) * np.sqrt(annual_factor)


# 성과 지표 계산 함수 (파라미터화)
def calculate_performance_metrics(returns, annual_factor=252, risk_free_rate=0.0):
    cumulative_returns = (1 + returns).cumprod()
    # cagr = calculate_cagr(returns, annual_factor)
    annual_return = calculate_annual_return(returns, annual_factor)
    sharpe_ratio = calculate_sharpe_ratio(returns, risk_free_rate, annual_factor)
    mdd = calculate_max_drawdown(returns)
    volatility = calculate_volatility(returns, annual_factor)

    return {
        'Cumulative Return': cumulative_returns.iloc[-1] - 1,
        'Annual Return': annual_return,
        # 'CAGR': cagr,
        'Volatility': volatility,
        'Sharpe Ratio': sharpe_ratio,
        'MDD': mdd
    }


# 성과 지표 요약 생성 함수 (파라미터 전달)
def get_performance_summary(returns_dict, annual_factor=252, risk_free_rate=0.0):
    metrics_df = pd.DataFrame()
    for name, returns in returns_dict.items():
        metrics_df[name] = calculate_performance_metrics(returns, annual_factor, risk_free_rate)
    return metrics_df.T

In [129]:
metrics_summary = get_performance_summary(
    strategy_returns,
    annual_factor=annual_factor,
    risk_free_rate=0.0
)

display(metrics_summary)

,Cumulative Return,Annual Return,Volatility,Sharpe Ratio,MDD
risk_parity,3.050437,0.063439,0.137658,0.460848,0.517716
minvar,5.754640,0.087624,0.098399,0.890500,0.346831
max_shapre,1.161621,0.034477,0.170528,0.202176,0.686945
paa,1.603418,0.042971,0.202794,0.211893,0.757277
Equal Weight,3.818659,0.071591,0.148739,0.481322,0.521208

In [130]:
strategy_returns

{'risk_parity': 2002-02-05   -0.004431
 2002-02-06   -0.003447
 2002-02-07    0.002515
 2002-02-08    0.006796
 2002-02-11    0.003493
                 ...
 2024-12-24    0.004355
 2024-12-26    0.002422
 2024-12-27   -0.002674
 2024-12-30   -0.002913
 2024-12-31    0.000422
 Length: 5731, dtype: float64,
 'minvar': 2002-02-05    0.007067
 2002-02-06   -0.000896
 2002-02-07   -0.000863
 2002-02-08    0.007633
 2002-02-11   -0.005547
                 ...
 2024-12-24    0.004629
 2024-12-26    0.002984
 2024-12-27   -0.002529
 2024-12-30    0.002319
 2024-12-31    0.003147
 Length: 5731, dtype: float64,
 'max_shapre': 2002-02-05   -0.007578
 2002-02-06    0.004537
 2002-02-07    0.012914
 2002-02-08    0.007345
 2002-02-11    0.007395
                 ...
 2024-12-24    0.008166
 2024-12-26   -0.002971
 2024-12-27   -0.012299
 2024-12-30    0.004256
 2024-12-31    0.000601
 Length: 5731, dtype: float64,
 'paa': 2002-02-05   -0.000850
 2002-02-06   -0.002986
 2002-02-07    0.003346
 2002-02-08    0.007071
 2002-02-11    0.000145
                 ...
 2024-12-24    0.021902
 2024-12-26   -0.028779
 2024-12-27   -0.030414
 2024-12-30    0.048404
 2024-12-31   -0.014668
 Length: 5731, dtype: float64,
 'Equal Weight': 2002-02-05   -0.009956
 2002-02-06   -0.003206
 2002-02-07    0.002745
 2002-02-08    0.006187
 2002-02-11    0.008076
                 ...
 2024-12-24    0.006031
 2024-12-26   -0.003351
 2024-12-27   -0.005881
 2024-12-30    0.004865
 2024-12-31   -0.001580
 Length: 5731, dtype: float64}